### ISSUE TITLE
Not receiving connection lost event when Vector is turned off

### ISSUE THREAD

**Issue by randym32** [codaris/Anki.Vector.SDK#2]
I am not receiving connection lost events when Vector is turned off, or powers himself off (eg when he is stuck/lost and his battery gets low).

I think the fix would be to add timers to the event stream handler, control response handler, and camera handler.  When a new event occurs there, it resets the timer.  When the timer expires, it would then raise a lost connection event, lost control event, etc.

This looks like it could interact with several other parts of the assembly.  So I thought it would be best to bring it up as an issue first, before making changes in lots places.  What would your prefer design be?

Thank-you and have a great day!

**Comment by codaris** [comment]
Hello Randy,

I just published a fix for this to the current branch.  The previous logic was any loss of the event stream was considered a disconnect and would shut everything down.  Unfortunately, as you noticed, when Vector is powered off there is no gPRC notification to shut down the streams.

I added a 5 second timeout to the event stream to trigger the stream shutdown as well as a flag to indicate that this is a connection loss disconnect.  This was necessary because a normal disconnect does a bunch of calls to Vector to properly shut everything down and that's not possible if he's been powered off.

I've tested it and it works well (my poor Vector has been rebooted so many times).  Grab the latest commit and you should be good to go.
